export const env = {
  REACT_APP_ENV: process.env.NODE_ENV,
  REACT_APP_ENV_BACKEND_HOST: process.env.REACT_APP_ENV_BACKEND_HOST,
  REACT_APP_ENV_ROLLBAR_SERVER_TOKEN: process.env.REACT_APP_ENV_ROLLBAR_SERVER_TOKEN
};
