export type FamilyItem = {
  UF: string;
  MUNICIPIO: string;
  TITULAR: string;
  DTNASCTIT: string;
  NISTITULAR: string;
  COMPETFOLHA: string;
  SITFAM: string;
  NISDEPENDEN: string;
  DEPENDENTE: string;
  IDADE: string;
  DTNASCDEP: string;
  'QTDE. MEMBROS': string;
};

export type SislameItem = {
  Escola: string;
  Matricula: string;
  Aluno: string;
  'Data Nascimento': string;
  'Condicao Matricula': string;
  'Situacao Aluno': string;
  'Nome Responsavel': string;
  Mae: string;
  Pai: string;
  Complemento: string;
};

export type OriginalSislameItem = {
  Escola: string;
  Matrícula: string;
  Aluno: string;
  'Data Nascimento': string;
  'Condição Matrícula': string;
  'Situação Aluno': string;
  'Nome Responsável': string;
  Mãe: string;
  Pai: string;
};

// All the fields from SISLAME
export type PureSislameItem = {
  SEE: string; // 'SECRETARIA DE ESTADO DA EDUCAÇÃO';
  SRE: string; // 'SRE JUIZ DE FORA';
  Prefeitura: string; // 'PREFEITURA MUNICIPAL DE JUIZ DE FORA';
  'Codigo Censo Escola': string; // '31217999';
  Escola: string; // 'EM HENRIQUE JOSÉ DE SOUZA';
  Nivel: string; // 'ENSINO FUNDAMENTAL';
  Etapa: string; // 'SÉTIMO ANO';
  'Identificador Turma': string; // '136434';
  Turma: string; // '7º Ano B';
  Turno: string; // 'MANHÃ';
  'Tipo Atendimento': string; // 'REGULAR';
  'Ano Administrativo': string; // '2020';
  Matricula: string; // '120067';
  Aluno: string; // 'VITÓRIA AUGUSTA PEDRO';
  'Nome Social': string; // '';
  'Id Aluno': string; // '1108772';
  'Codigo INEP': string; // '1,20592E+11';
  Sexo: string; // 'F';
  'Data Nascimento': string; // '27/10/2006';
  Etnia: string; // 'Preta';
  'Condicao Matricula': string; // 'REPETENTE';
  'Situacao Aluno': string; // 'Ativo';
  'Parentesco Responsavel': string; // 'Mãe';
  'Nome Responsavel': string; // '';
  'CPF Responsavel': string; // '';
  'E-mailResponsavel': string; // '';
  'Data Matrícula': string; // '17/01/2020 0:00';
  Mae: string; // 'SONIMAR DE FATIMA SILVA';
  Pai: string; // 'JORGE ADRIANO PEDRO';
  'Necessidades Especiais': string; // '';
  Logradouro: string; // 'AV. ANTONIO GUIMARÃES PERALVA';
  Nº: string; // '35';
  Bairro: string; // 'BARBOSA LAGE';
  Distrito: string; // '';
  Complemento: string; // '204';
  'ED. Município': string; // 'JUIZ DE FORA';
  UF: string; // 'MG';
  Telefone: string; // '(32) 8832-6758';
  'Telefone Celular': string; // '';
  CEP: string; // '36085-17';
  CPF: string; // '';
  RG: string; // '';
  'RG Complemento': string; // '';
  'RG Data Emissao': string; // '';
  'RG Orgão Emissor': string; // '';
  'RG - UF': string; // '';
  'Transporte Público': string; // 'Não Utiliza';
  'Ano Inicio Período': string; // '2020';
  'Ano Termino Período': string; // '2020';
  Cegueira: string; // 'Não';
  'Baixa Visão': string; // 'Não';
  Surdez: string; // 'Não';
  'Deficiencia Auditiva': string; // 'Não';
  'Deficiencia Física': string; // 'Não';
  'Deficiencia Multipla': string; // 'Não';
  'Autismo Infantil': string; // 'Não';
  'Sindrome de Asperger': string; // 'Não';
  'Sindrome de Rett': string; // 'Não';
  'Transtorno Desintegrativo da Infancia': string; // 'Não';
  'Altas Habilidades/Superdotacao': string; // 'Não';
  Surdocegueira: string; // 'Não';
  'Deficencia Intelectual': string; // 'Não';
};
