export const env = {
  REACT_APP_ENV: process.env.NODE_ENV,
  REACT_APP_ENV_BACKEND_HOST: process.env.REACT_APP_ENV_BACKEND_HOST,
  REACT_APP_ENV_ROLLBAR_SERVER_TOKEN: process.env.REACT_APP_ENV_ROLLBAR_SERVER_TOKEN,
  REACT_APP_ENV_CITY_ID: process.env.REACT_APP_ENV_CITY_ID,
  REACT_APP_ENV_CITY_NAME: process.env.REACT_APP_ENV_CITY_NAME,
  REACT_APP_ENV_INFO_LINK: process.env.REACT_APP_ENV_INFO_LINK,
  REACT_APP_ENV_INFO_PHONE: process.env.REACT_APP_ENV_INFO_PHONE
};
